### ISSUE TITLE
Search / Auto complete

### ISSUE THREAD

**Issue by micrie** [digitaldesaster/Emma-for-Spotify-TV#18]
When starting to type in a search pattern, an auto complete should be done as a small pull down menu or something like that. For example: link -> Linkin Park, prod -> The Prodigy

Like in the Windows Client

**Comment by digitaldesaster** [comment]
i have to be careful regarding the api calls.. every type of a letter would cause  a few api calls. i understand that this is a useful feature, but at the moment i will not put it on the roadmap.
