### ISSUE TITLE
Show "My Library" in Emma Navigation Pane

### ISSUE THREAD

**Issue by micrie** [digitaldesaster/Emma-for-Spotify-TV#22]
Possibility to access my library in the left navigation pane.

**Comment by digitaldesaster** [comment]
please describe more in detail.

**Comment by micrie** [comment]
In the left navigation pane there is "Main / New / Featured / Categories / Recently played / More"

It would be great if there is also a navigation point "My Library"

**Comment by digitaldesaster** [comment]
please check 0.87! it should be live this afternoon or tomorrow
